# Makefile para ejercicios en lex

# Lex
L = lex

# Compilador 
CC = gcc
FLAGS = -lfl

lex:	ejercicios limpiar

ejercicios:	ej01 ej02 ej03 ej04 ej05 ej06 ej08 ej09 ej10

ej01:		
		$(L) -o ej01.c ej01.lex 
		$(CC) -o ej01 ej01.c $(FLAGS)
		
ej02:		
		$(L) -o ej02.c ej02.lex 
		$(CC) -o ej02 ej02.c $(FLAGS)
		
ej03:		
		$(L) -o ej03.c ej03.lex 
		$(CC) -o ej03 ej03.c $(FLAGS)
		
ej04:		
		$(L) -o ej04.c ej04.lex 
		$(CC) -o ej04 ej04.c $(FLAGS)
		
ej05:		
		$(L) -o ej05.c ej05.lex 
		$(CC) -o ej05 ej05.c $(FLAGS)
		
ej06:		
		$(L) -o ej06.c ej06.lex 
		$(CC) -o ej06 ej06.c $(FLAGS)
		
ej08:		
		$(L) -o ej08.c ej08.lex 
		$(CC) -o ej08 ej08.c $(FLAGS)
		
ej09:		
		$(L) -o ej09.c ej09.lex 
		$(CC) -o ej09 ej09.c $(FLAGS)
		
ej10:	
		$(L) -o ej10.c ej10.lex 
		$(CC) -o ej10 ej10.c $(FLAGS)
		
limpiar:
		rm ej01.c ej01.o
		rm ej02.c ej02.o
		rm ej03.c ej03.o
		rm ej04.c ej04.o
		rm ej05.c ej05.o
		rm ej06.c ej06.o
		rm ej08.c ej08.o
		rm ej09.c ej09.o
		rm ej10.c ej10.o